name: Delete Oldest Vectors

on:
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest
    env:
      QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Delete Oldest Vectors
        run: python check_and_delete.py 